apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-service-demo-1
  labels:
    app: service-demo-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-demo-1
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
