apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: test
resources:
  - ../../base/traefik-v2/
patchesStrategicMerge:
  - traefik-config.yaml
  - tls-traefik-ingress.yaml
  - ingressroute-traefik-mgmt-http.yaml
